TailorBrands/tailor-rubocop

rubocop.yml
These are the default rules, following the official ruby styleguide: https://github.com/rubocop-hq/ruby-style-guide
With these minor changes:
- Remove the ABC analyzer, it created to much mess
- Remove the mandatory class & modules documentations
- Line length raised from 80 to 120
- Method length raised to 15 (as it was raised in most of our repos before)
- Trailing commas: the official styleguide says no, we say yes.
- Prefer '' over "" when no string interpolation: canceled. always "".
- Won't let you use more than 3 parameters for method. Change to keyword args.
- Allow case equality (===), it makes regex checks more readable
- `Naming/PredicateName` is disabled. It prevents adding `has_` or `is_` to method names, and that sometimes make the code less readable.
- Classes can be as …
=> Add rubocop configuration

rubocop.yml
- Allow long lines for guard statements
- Disable class length cop
- Change default err var name to `err`
- String and Symbols array prefer brackets syntax always
=> Update rubocop rules

rubocop.yml
Use `brace_for_chaining` rule, as it looks more familiar having `}.something` than `end.something`
=> Block delimiter rule change

rubocop.yml
=> Change indentation to match defaul rubymine, disable line length

rubocop.yml
To have a workable version for tailor-core, we have to relax some rules.
They are divided as such:
- ParameterLists - lower restriction back to 3.
- MemoizedInstanceVariableName
- MethodParameterName (to make sure no parameters named `a` or `x`)
- GlobalVars
- CircularArgumentReference
- Void
- BlockLength
- MethodLength
- AccessorMethodName
- ClassVars
- FloatDivision
- IfUnlessModifier
- MultilineBlockChain
=> Relax rules for tailor core

rubocop.yml
prefixed unlesses open up the possibility for more complex block comparisons that are sometimes hard to follow
I propose to disallow prefix unless altogether
```
bar if !foo
bar unless foo
if !foo
bar
end
```
=> Disallow prefixed unless

rubocop.yml
Since Ruby 2.7, the existence of curly braces on the last argument has meaning.
It means, the following codes have different meanings.
```rb
foo(x: 1) # x: 1 is a keyword argument
foo({x: 1}) # {x: 1} is a hash
```
There are the correct pairs of method definitions and method calls.
```rb
def foo(x: 1)
end
foo(x: 1)
def foo(hash)
end
foo({x: 1})
```
For more detail https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
* Taken from https://github.com/rubocop-hq/rubocop/issues/7641
* remove Style/BracesAroundHashParameters
=> Remove Style/BracesAroundHashParameters

rubocop.yml
Clear obsolete rules from `rubocop` configuration - as spotted when running lint process on `sitcom` project (for example):
```
Error: The `Layout/Tab` cop has been renamed to `Layout/IndentationStyle`.
(obsolete configuration found in .rubocop-https---raw-githubusercontent-com-TailorBrands-tailor-rubocop-master-rubocop-yml, please update it)
The `Lint/EndInMethod` cop has been renamed to `Style/EndBlock`.
(obsolete configuration found in .rubocop-https---raw-githubusercontent-com-TailorBrands-tailor-rubocop-master-rubocop-yml, please update it)
The `Lint/UselessComparison` cop has been removed since it has been superseded by `Lint/BinaryOperatorWithIdenticalOperands`. Please use `Lint/BinaryOperatorWithIdenticalOperands` instead.
(obsolete configuration found in …
```
=> Clear obsolete rules from rubocop configuration

rubocop.yml
Reapply the next rules:
- `Metrics/ParameterLists` - allow max of 3 non key parameters
- `Naming/MemoizedInstanceVariableName` - turn back on
- `Naming/MethodParameterName` - turn back on
- `Style/GlobalVars` - turn back on
- `Lint/CircularArgumentReference` - turn back on
=> Re-apply some rules back

rubocop.yml
Fix enabled flag for Layout/SpaceBeforeBrackets rule. Fix this error: `Property Enabled of cop Layout/SpaceBeforeBrackets is supposed to be a boolean and pending is not.`
=> Fix enabled flag for Layout/SpaceBeforeBrackets rule

rubocop.yml
Fix Migration/DepartmentName rule
=> Fix Migration/DepartmentName rule

rubocop.yml
Fix:
```
error: Unsafe cops cannot have a safe auto-correction (section Style/InfiniteLoop in .rubocop-https---raw-githubusercontent-com-TailorBrands-tailor-rubocop-master-rubocop-yml)
```
=> Remove safe auto-correct from Style/InfiniteLoop

rubocop.yml
=> Disable Metrics/AbcSize rule

rubocop.yml
Fix obsolete warnings:
```
Warning: obsolete parameter `ExcludedMethods` (for `Metrics/BlockLength`) found in .rubocop-https---raw-githubusercontent-com-TailorBrands-tailor-rubocop-master-rubocop-yml
`ExcludedMethods` has been renamed to `IgnoredMethods`.
obsolete parameter `ExcludedMethods` (for `Metrics/MethodLength`) found in .rubocop-https---raw-githubusercontent-com-TailorBrands-tailor-rubocop-master-rubocop-yml
`ExcludedMethods` has been renamed to `IgnoredMethods`.
Warning: Style/SymbolProc does not support SafeAutoCorrect parameter.
- Enabled
- IgnoredMethods
Warning: obsolete parameter `ExcludedMethods` (for `Metrics/BlockLength`) found in .rubocop.yml
`ExcludedMethods` has been renamed to `IgnoredMethods`.
obsolete parameter `ExcludedMethods` (for …
```
=> Fix obselete warnings

rubocop.yml
Disable Lint/MissingSuper Rule
=> Disable Lint/MissingSuper Rule

rubocop.yml
Fix description for Migration/DepartmentName rule
=> Fix description for Migration/DepartmentName rule

rubocop.yml
Disable all pending rules - otherwise, it gives a warning that `pending` is not a valid boolean value when running rubocop locally
=> Disable all pending rules

rubocop.yml
Turn off Style/HashAsLastArrayItem rule
=> Turn off Style/HashAsLastArrayItem rule

rubocop.yml
Clear rubocop warnings
```
.rubocop-https---raw-githubusercontent-com-TailorBrands-tailor-rubocop-master-rubocop-yml:1272: `VersionAdded` is concealed by line 1274
Warning: obsolete parameter `ExcludedMethods` (for `Metrics/BlockLength`) found in .rubocop-https---raw-githubusercontent-com-TailorBrands-tailor-rubocop-master-rubocop-yml
`ExcludedMethods` has been renamed to `IgnoredMethods`.
obsolete parameter `ExcludedMethods` (for `Metrics/MethodLength`) found in .rubocop-https---raw-githubusercontent-com-TailorBrands-tailor-rubocop-master-rubocop-yml
`ExcludedMethods` has been renamed to `IgnoredMethods`.
Warning: Layout/SpaceBeforeBrackets does not support Safe parameter.
- Enabled
```
=> Clear rubocop warnings

rubocop.yml
Done using: https://docs.rubocop.org/rubocop/1.7/configuration.html#updating-the-configuration-file
=> Align rubocop.yml with version 1.8.1

rubocop.yml
Increase threshold for Metrics/ParameterLists to 15 parameters
=> Increase threshold for Metrics/ParameterLists to 15 parameters

rubocop.yml
Update rubocop configuration to the latest version, this change is done in order to clear the current warnings we have during the lint run process in GitHub workflow:
```
`Layout/FirstArgumentIndentation` is concealed by line 770
Warning: obsolete parameter `ExcludedMethods` (for `Metrics/BlockLength`) found in .rubocop-https---raw-githubusercontent-com-TailorBrands-tailor-rubocop-master-rubocop-yml
`ExcludedMethods` has been renamed to `IgnoredMethods`.
obsolete parameter `ExcludedMethods` (for `Metrics/MethodLength`) found in .rubocop-https---raw-githubusercontent-com-TailorBrands-tailor-rubocop-master-rubocop-yml
`ExcludedMethods` has been renamed to `IgnoredMethods`.
Warning: Style/ExplicitBlockArgument does not support Safe parameter.
- Enabled
Error: …
```
=> Update rubocop configuration to the latest version

rubocop.yml
Align Rubocop configuration files with updated definitions
=> Align Rubocop configuration files with updated definitions

rubocop.yml
Remove redundant rule -
```
Error: unrecognized cop or department Lint/RequireRelativeSelfPath found in .rubocop-https---raw-githubusercontent-com-TailorBrands-tailor-rubocop-master-rubocop-yml
Did you mean `Lint/RequireParentheses`?
```
=> Remove redundant rule

rubocop.yml
Modify optional parameters count - needed mostly for workers - since we are not able to send named parameters to Sidekiq workers as an input
=> Modify optional parameters count

rubocop.yml
Fix the next lint warning: 
```
Warning: Lint/InheritException does not support VersionChanged parameter.
- Enabled
- EnforcedStyle
- SupportedStyles
Warning: Lint/InheritException does not support VersionChanged parameter.
```
=> Remove wrong parameter from Lint/InheritException cop

rubocop.yml
Align rubocop configuration to latest rubocop version
=> Align rubocop configuration to latest rubocop version

rubocop.yml
Align Rubocop configuration to new Rubocop version. Taken from: https://raw.githubusercontent.com/rubocop/rubocop/master/config/default.yml
=> Align Rubocop configuration to new Rubocop version

rubocop.yml
```
Warning: obsolete parameter `AllowOnlyRestArgument` (for `Style/ArgumentsForwarding`) found in .rubocop-https---raw-githubusercontent-com-TailorBrands-tailor-rubocop-master-rubocop-yml
`AllowOnlyRestArgument` has no effect with TargetRubyVersion >= 3.2.
Warning: Layout/LineContinuationSpacing does not support SafeAutoCorrect parameter.
- Enabled
- EnforcedStyle
- SupportedStyles
Warning: Lint/UselessMethodDefinition does not support AllowComments parameter.
- Enabled
- AutoCorrect
Warning: obsolete parameter `AllowOnlyRestArgument` (for `Style/ArgumentsForwarding`) found in .rubocop.yml
`AllowOnlyRestArgument` has no effect with TargetRubyVersion >= 3.2.
Warning: Layout/LineContinuationSpacing does not support SafeAutoCorrect …
```
=> Fix deprecated configuration

rubocop.yml
In this PR - I would like to disable `RSpec/MultipleMemoizedHelpers` rubocop rule since I'm not sure this is a rule we would need to be strict about  - https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecmultiplememoizedhelpers
=> Disable redundant `RSpec/MultipleMemoizedHelpers` rubocop rule
